#!/bin/bash

cd $(dirname "$0")
. ../bash-plop/bash-plop.sh

plop_setup()
{
	full_num=$(printf '%0*d' $PLOP_MIN_NUM_LENGTH $PLOP_TEST_NUM)
	PLOP_TEST_OUTPUT="outs/test-$full_num.txt"
}

plop_init

if ! [ -f config.vars ]
then
	echo "# This file was automatically generated by the CPP-Modules-tester" > config.vars
	echo "# https://github.com/vfurmane/CPP-Modules-tester" >> config.vars
	echo >> config.vars
	plop_ask_config "Project directory" ".."
	echo "PROJECT_DIRECTORY='$PLOP_CONFIG_ANSWER'" >> config.vars
fi
. config.vars

mkdir -p outs

printf "${BOLD}ex 00${NC}\n\n"
if [ -d "$PROJECT_DIRECTORY/ex00" ]
then
	PLOP_DESCRIPTION="The exercise compiles"
	plop_test_command make -C "$PROJECT_DIRECTORY/ex00"
	[ $PLOP_EXIT_STATUS -ne 0 ] \
		&& PLOP_TEST_RESULT="KO"
	plop_test_summary

	echo -e "\n${UNDERLINE}./megaphone \"shhhhh... I think the students are asleep...\"${NC}"
	PLOP_DESCRIPTION="The command works"
	plop_test_command "$PROJECT_DIRECTORY/ex00/megaphone" "shhhhh... I think the students are asleep..."
	[ $PLOP_EXIT_STATUS -ne 0 ] \
		&& PLOP_TEST_RESULT="KO"
	diff refs/subject-example-1.txt outs/test-$full_num.txt > /dev/null 2>&1 \
		|| PLOP_TEST_RESULT="KO"
	plop_test_summary

	echo -e "\n${UNDERLINE}./megaphone Damnit \" ! \" \"Sorry students, I thought this thing was off.\"${NC}"
	PLOP_DESCRIPTION="The command works"
	plop_test_command "$PROJECT_DIRECTORY/ex00/megaphone" Damnit " ! " "Sorry students, I thought this thing was off."
	[ $PLOP_EXIT_STATUS -ne 0 ] \
		&& PLOP_TEST_RESULT="KO"
	diff refs/subject-example-2.txt outs/test-$full_num.txt > /dev/null 2>&1 \
		|| PLOP_TEST_RESULT="KO"
	plop_test_summary

	echo -e "\n${UNDERLINE}./megaphone${NC}"
	PLOP_DESCRIPTION="The command works"
	plop_test_command "$PROJECT_DIRECTORY/ex00/megaphone"
	[ $PLOP_EXIT_STATUS -ne 0 ] \
		&& PLOP_TEST_RESULT="KO"
	diff refs/subject-example-3.txt outs/test-$full_num.txt > /dev/null 2>&1 \
		|| PLOP_TEST_RESULT="KO"
	plop_test_summary
else
	printf "${YELLOW}ex00: nothing turned in${NC}\n"
fi

plop_end
